# Generated by Django 4.2.3 on 2023-07-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='team')),
                ('stata', models.CharField(max_length=250)),
                ('stata_description', models.TextField()),
            ],
        ),
    ]
